name: five_wheel
description: A base flutter project for apps
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  cached_network_image: ^3.3.1
  collection: ^1.17.2
  dio: ^5.3.3
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.4.0
  flutter_svg: ^2.0.9
  freezed_annotation: ^2.4.1
  go_router: ^10.1.2
  intl: ^0.18.1
  json_annotation: ^4.8.1
  palette_generator: ^0.3.3+3
  path_provider: ^2.1.1
  riverpod_annotation: ^2.1.5
  slang: ^3.24.0
  slang_flutter: ^3.24.0
  supabase_flutter: ^2.2.0
  uuid: ^4.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  freezed: ^2.4.1
  riverpod_generator: ^2.3.2
  build_runner: ^2.4.6
  custom_lint: ^0.5.3
  riverpod_lint: ^2.1.0
  json_serializable: ^6.7.1
  slang_build_runner: ^3.24.0

flutter:
  uses-material-design: true
  assets:
    - assets/i18n/
    - assets/images/
    - assets/images/icons/
    - assets/images/flags/

  fonts:
    - family: NotoSans
      fonts:
        - asset: assets/fonts/noto_sans/NotoSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/noto_sans/NotoSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/noto_sans/NotoSans-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/noto_sans/NotoSans-Light.ttf
          weight: 300
        - asset: assets/fonts/noto_sans/NotoSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/noto_sans/NotoSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/noto_sans/NotoSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/noto_sans/NotoSans-Thin.ttf
          weight: 100